-d D:\gaoyunfpgademo\m3demo1\keyin_run\fpga_keyin\impl\gwsynthesis\fpga_led.vg
-p GW1NS-4C-QFN48-7
-pn GW1NS-LV4CQN48C7/I6
-cst D:\gaoyunfpgademo\m3demo1\keyin_run\fpga_keyin\src\top.cst
-cfg D:\gaoyunfpgademo\m3demo1\keyin_run\fpga_keyin\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
