-d C:\Users\A\Desktop\TANG\gowin\projects\nano_viewer\impl\gwsynthesis\nano_viewer.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst C:\Users\A\Desktop\TANG\gowin\projects\nano_viewer\src\nano_viewer.cst
-cfg C:\Users\A\Desktop\TANG\gowin\projects\nano_viewer\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
