-d C:\Users\Andrew Dudaronek\Desktop\MiniStar-main\MiniStar-main\projects\Led Demo\led_run\fpga_led\impl\gwsynthesis\fpga_led.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst C:\Users\Andrew Dudaronek\Desktop\MiniStar-main\MiniStar-main\projects\Led Demo\led_run\fpga_led\src\top.cst
-cfg C:\Users\Andrew Dudaronek\Desktop\MiniStar-main\MiniStar-main\projects\Led Demo\led_run\fpga_led\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
