-d C:\Users\wu\Desktop\gw_dds\DDS\impl\gwsynthesis\DDS.vg
-p GW1N-1-QFN48-6
-pn GW1N-LV1QN48C6/I5
-cst C:\Users\wu\Desktop\gw_dds\DDS\src\DDS.cst
-cfg C:\Users\wu\Desktop\gw_dds\DDS\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
