-d F:\0_code\Gowin\ministar_eth_audio\FPGA_Design\impl\gwsynthesis\gowin_empu_hyperram.vg
-p GW1NSR-4C-QFN48P-7
-pn GW1NSR-LV4CQN48PC7/I6
-cst F:\0_code\Gowin\ministar_eth_audio\FPGA_Design\src\gowin_empu.cst
-cfg F:\0_code\Gowin\ministar_eth_audio\FPGA_Design\impl\pnr\device.cfg
-sdc F:\0_code\Gowin\ministar_eth_audio\FPGA_Design\src\gowin_empu_hyperram.sdc
-bit
-tr
-ph
-timing
-cst_error
