-d G:\Gowin\Gowin_V1.9.7.06Beta_GowinSynthesis-only\workspace\my_gowin_spi_lcd\impl\gwsynthesis\my_gowin_spi_lcd.vg
-p GW1NSR-4C-QFN48P-7
-pn GW1NSR-LV4CQN48PC7/I6
-cst G:\Gowin\Gowin_V1.9.7.06Beta_GowinSynthesis-only\workspace\my_gowin_spi_lcd\src\my_gowin_spi_lcd.cst
-cfg G:\Gowin\Gowin_V1.9.7.06Beta_GowinSynthesis-only\workspace\my_gowin_spi_lcd\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
